module.exports = {
    AUTHORIZATION: 'Authorization',
    CAR: 'Car',
    CARS: 'cars',
    CASCADE: 'CASCADE',
    FEMALE: 'female',
    FILE: 'File',
    FILES: 'files',
    LOCALHOST: 'localhost',
    MALE: 'male',
    NO_REPLY: 'no reply',
    OAUTH: 'OAuth',
    O_AUTH: 'o_auth',
    STUDENT: 'Student',
    STUDENTS: 'students',
};
