module.exports = {
    DATABASE_USERNAME: process.env.DATABASE_USERNAME,
    DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
    ACCESS_TOKEN_WORD: process.env.ACCESS_TOKEN_WORD,
    REFRESH_TOKEN_WORD: process.env.REFRESH_TOKEN_WORD,
    HOST_NAME: process.env.HOST_NAME,
};
